### ISSUE TITLE
Make Highest Score persistant

### ISSUE THREAD

**Issue by pirateksh** [ContriHUB/Battleship-web-game#4]
**[Unlocks after #3 is complete]**
Make the Highest Score value persistent using Browser's Local Storage or Cookies. 
(The Highest Score must be saved every time user visits the Game).

**Comment by kunal2812** [comment]
Looks like previous assignee already solved this issue along with #3. The score already persists :(

**Comment by pirateksh** [comment]
> Looks like previous assignee already solved this issue along with #3. The score already persists :(

Yes, but that's why I did not  merge it to give you a chance as well. You can implement this feature but make sure that code should not be similar to PR linking to Issue #3 .

**Comment by pirateksh** [comment]
@kunal2812  Are you interested in solving this issue?

**Comment by kunal2812** [comment]
Yes sir, I was going to start the work. Revengg-ing at the moment :yum:
